version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularNodeModules-{{ .Branch }}-{{ checksum "frontend/package.json" }}
      - run:
          name: Installing frontend dependencies
          working_directory: frontend
          command: npm install
      - save_cache:
          key: AngularNodeModules-{{ .Branch }}-{{ checksum "frontend/package.json" }}
          paths:
            - "node_modules"
      - restore_cache:
          key: BackendNodeModules-{{ .Branch }}-{{ checksum "backend/core/package.json" }}
      - run:
          name: Installing backend core dependencies
          working_directory: backend/core
          command: npm install
      - save_cache:
          key: BackendNodeModules-{{ .Branch }}-{{ checksum "backend/core/package.json" }}
          paths:
           - "node_modules"
      - run:
          name: Running frontend tests
          working_directory: frontend
          command: npm run test:ci
      - run:
          name: Running backend core tests
          working_directory: backend/core
          command: npm run test:ci
      - run:
          name: Installing serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: Deploying frontend to AWS using serverless CLI
          working_directory: frontend
          command: serverless deploy
      - run:
          name: Packaging backend core
          working_directory: backend/core
          command: npm run package
      - run:
          name: Deploying backend core to AWS using serverless CLI
          working_directory: backend/core
          command: backend/core
