app: skill-dating-app-backend
component: aws-dynamodb
name: user-profile-table

inputs:
  name: ${name}-${stage}
  region: eu-central-1
  deletionPolicy: delete
  attributeDefinitions:
    - AttributeName: PK
      AttributeType: S
    - AttributeName: SK
      AttributeType: S
  keySchema:
    - AttributeName: PK
      KeyType: HASH
    - AttributeName: SK
      KeyType: RANGE
  globalSecondaryIndexes:
    - IndexName: SKILL_GSI
      KeySchema:
        - AttributeName: SK
          KeyType: HASH
      Projection:
        ProjectionType: ALL
